"""설계 문서의 교체 경계 (ADR-021). 오픈소스 호출은 adapters/ 안에만 둔다."""
from __future__ import annotations

from typing import Any, Iterable, Protocol

import numpy as np

from .model import Document, Edge, RawItem


class Connector(Protocol):
    name: str

    def fetch(self) -> Iterable[RawItem]: ...


class Repository(Protocol):
    def upsert_document(self, doc: Document, run_id: str) -> bool: ...
    def get_document(self, doc_id: str) -> dict[str, Any] | None: ...
    def all_documents(self) -> list[dict[str, Any]]: ...
    def replace_edges(self, edges: list[Edge]) -> None: ...
    def edges(self) -> list[Edge]: ...
    def history(self, doc_id: str) -> list[dict[str, Any]]: ...


class SearchIndex(Protocol):
    """키워드 인덱스 (한국어 분석 포함)."""
    def rebuild(self, docs: list[dict[str, Any]], user_words: list[str], synonyms: list[list[str]]) -> None: ...
    def search(self, query: str, k: int = 50, filters: dict[str, str] | None = None) -> list[tuple[str, float]]: ...


class Analyzer(Protocol):
    def tokens(self, text: str) -> list[str]: ...


class Embedder(Protocol):
    dim: int

    def embed(self, texts: list[str]) -> np.ndarray: ...


class VectorIndex(Protocol):
    def rebuild(self, ids: list[str], vectors: np.ndarray) -> None: ...
    def search(self, vector: np.ndarray, k: int = 50) -> list[tuple[str, float]]: ...


class LLMClient(Protocol):
    def complete_json(self, system: str, user: str, schema: type) -> Any: ...


class GraphService(Protocol):
    def downstream(self, entity: str, hops: int = 3) -> list[dict[str, Any]]: ...
    def upstream(self, entity: str, hops: int = 3) -> list[dict[str, Any]]: ...
    def neighbors(self, entity: str) -> list[Edge]: ...
